### ISSUE TITLE
app_manager plugin with machine tag

### ISSUE THREAD

**Issue by tkmtnt7000** [knorth55/app_manager_utils#29]
i want to run app_manager plugins with machine tag.
I want to run `audio_video_recorder` in C2 of PR2.

cc. @708yamaguchi

**Comment by 708yamaguchi** [comment]
Do you mean that we should edit `app_manager.py` to use `add_machine()`?

https://github.com/ros/ros_comm/blob/07fb5469c71e10e4a05fa3a631897d9adece61c5/tools/roslaunch/src/roslaunch/config.py#L322

https://github.com/isaac-jordan/ros-multirobot-evaluation/blob/49618d35144a9a6c27d398187bae56628d2733a5/experiments/message_latency/vertical_scaling/roslaunch_script.py#L35-L43

**Comment by knorth55** [comment]
i think just adding `machine` yaml argument for `launch_args` in app manager plugins.

**Comment by 708yamaguchi** [comment]
Oh, I see. That's the easiest way.

**Comment by 708yamaguchi** [comment]
This issue will be solved in https://github.com/knorth55/app_manager_utils/pull/32 and https://github.com/knorth55/jsk_demos/pull/21

I think this issue is ok to close.

**Comment by knorth55** [comment]
thank you!

**Comment by knorth55** [comment]
machine tag is not implemented in rosbag recorders, which caused upload error.
file saving place depends on machine tag, and we need to run `c1` `/gdrive_server` and `c2` `/gdrive_server_c2` to upload files properly.

**Comment by knorth55** [comment]
result recorder cannot be machine tag because it is python plugin of `app_manager`.
