### ISSUE TITLE
app_recorder records compressed image

### ISSUE THREAD

**Issue by tkmtnt7000** [knorth55/app_manager_utils#30]
I want to record videos with compressed image topic.

cc @708yamaguchi

**Comment by knorth55** [comment]
this is related to https://github.com/knorth55/audio_video_recorder/issues/1

**Comment by 708yamaguchi** [comment]
I created PR https://github.com/knorth55/app_manager_utils/pull/31.

I checked that following code works well with PR1040.

```bash
roslaunch app_recorder video_recorder.launch video_compressed_topic_name:=/kinect_head/rgb/throttled/image_rect_color video_topic_name:=/kinect_head_remote/rgb/throttled video_path:=/tmp video_title:=go_to_kitchen_object_detection.avi video_fps:=5.0 use_compressed:=true
```

I will create another PR to `rwt_teleop` app to use this PR

**Comment by knorth55** [comment]
@708yamaguchi can you try with `/kinect_head/rgb/image_rect_color/compresssed` for video recording?

**Comment by 708yamaguchi** [comment]
OK

This works well. 
```
roslaunch app_recorder video_recorder.launch video_compressed_topic_name:=/kinect_head/rgb/image_rect_color video_topic_name:=/kinect_head_remote/rgb/image_rect_color video_path:=/tmp video_title:=go_to_kitchen_object_detection.avi video_fps:=5.0 use_compressed:=true
```

I checked that the compressed image topic is subscribed.
```
$ rostopic info /kinect_head/rgb/image_rect_color/compressed
```

**Comment by 708yamaguchi** [comment]
This issue will be solved in https://github.com/knorth55/app_manager_utils/pull/31 and https://github.com/knorth55/jsk_demos/pull/20.

I think this issue is ok to close.

**Comment by knorth55** [comment]
thank you!
