### ISSUE TITLE
dateutils>=2.7.0 is required but it is not installed with apt

### ISSUE THREAD

**Issue by sktometometo** [knorth55/app_manager_utils#33]
app_notifier use `dateutil.parser.isoparse` which is not available with dateutil==2.6.1 ( version of debian package `python-dateutil` ) 

c.f. https://github.com/conan-io/conan/issues/5484

**Comment by knorth55** [comment]
Yes, actually I know it.
Do you know any alternative for this issue?

**Comment by knorth55** [comment]
I add this commit: https://github.com/knorth55/app_manager_utils/commit/4d2d3ee9be8715254377f9285f3518b6a553fd7f

**Comment by sktometometo** [comment]
just for reminder. but thank you for fix.
